#!/bin/bash

# this virtualenv constructor does not create cython or lxml
# this virtualenv constructor also doesn't make the virtualenv relocateable
# virtualenv --relocatable venv   # should be done after installing all modules with pip

virtualenv venv

. venv/bin/activate

pip install beautifulsoup4

deactivate

#####  acoording to this documentation below apparently is a python module for setting up directory isolated from the rest of the 
#####  computer.  don't understand this concept
#####  also don't understand how this is a python module when it's a bash command

##### The venv module provides support for creating lightweight “virtual environments” with their own site directories, optionally isolated from system site directories. Each virtual environment has its own Python binary (allowing creation of environments with various Python versions) and can have its own independent set of installed Python packages in its site directories.
